data.raw['assembling-machine']["distilator"].working_sound.sound.filename = "__migrainefriendlypy__/sounds/distilator.ogg"
data.raw['assembling-machine']["distilator"].working_sound.idle_sound.filename = "__migrainefriendlypy__/sounds/distilator.ogg"
data.raw['assembling-machine']["distilator-mk02"].working_sound.sound.filename = "__migrainefriendlypy__/sounds/distilator.ogg"
data.raw['assembling-machine']["distilator-mk02"].working_sound.idle_sound.filename = "__migrainefriendlypy__/sounds/distilator.ogg"
data.raw['assembling-machine']["distilator-mk03"].working_sound.sound.filename = "__migrainefriendlypy__/sounds/distilator.ogg"
data.raw['assembling-machine']["distilator-mk03"].working_sound.idle_sound.filename = "__migrainefriendlypy__/sounds/distilator.ogg"
data.raw['assembling-machine']["distilator-mk04"].working_sound.sound.filename = "__migrainefriendlypy__/sounds/distilator.ogg"
data.raw['assembling-machine']["distilator-mk04"].working_sound.idle_sound.filename = "__migrainefriendlypy__/sounds/distilator.ogg"
